# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name : Set up Node Build front with node
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    
    - name : Set up Node Build front with node
      working-directory: menus-ionic
      run: npm install && npm run build
    
    - name: Copy front to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "menus-front/www"
        target: "work/dist_from_github"
