# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploying to food-organisator

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build back with Maven
      working-directory: menus-back
      run: mvn -B package --file pom.xml
      
    - name: Copy back to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "menus-back/target/menus-back.war"
        target: "work/dist_from_github"
    - name : Set up Node Build front with node
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    
    - name : Build front
      working-directory: menus-ionic
      run: npm install && npm run build
    
    - name: Copy front to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "menus-ionic/www"
        target: "work/dist_from_github"
